popsize=50  # 种群大小
model_num=50  # 代理模型数量
select_num=25  # 选择的模型数量
boot_prob=0.5  # 模型选择概率
machine_pro=0.5  # 机器选择最短概率
cross_prob=0.8  # 交叉概率
mutation_prob = 0.01  # 变异概率
generation=80  # 迭代次数，终止条件
swarm_size=25  # 粒子数目
param=[0.9,2,2]  # 粒子群算法参数 w,c1,c2
k=3   # 聚类中心数量
tournament_size = 2  # 锦标赛选择策略选择元数
